from enum import Enum


class Antibiotics(Enum):
    BENZYLPENICILLIN = 1
    AMPICILLIN = 2
    CEFOXITIN = 3
    CEFTAROLINE = 4
    CEFTOBIPROLE = 5
    CEFTRIAXONE = 6
    IMIPENEM = 7
    MEROPENEM = 8
    CIPROFLAXIN = 9
    LEVOFLAXIN = 10
    GENATMICIN = 11
    DALBAVANCIN = 12
    TEICOPLANIN = 13
    VANCOMYSIN = 14
    ERYTHROMYCIN = 15
    CLINDAMYCIN = 16
    TETRACYCLINE = 17
    LINEZOLID = 18
    DAPTOMYCIN = 19
    RIFAMPICIN = 20
    TRIMETHOPRIMSULFAMETHOXAZOLE = 21
    DTEST = 22
    OPTOCHIN = 23
